# Generated by Django 5.2.16 on 2026-08-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0002_booking_security_deposit_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="photos",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="review",
            name="replied_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="reply",
            field=models.TextField(blank=True),
        ),
    ]
