# Generated by Django 5.2.16 on 2026-08-11 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0006_emaildeliverylog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("booking_request", "Booking Request"),
                    ("booking_approved", "Booking Approved"),
                    ("booking_rejected", "Booking Rejected"),
                    ("booking_cancelled", "Booking Cancelled"),
                    ("new_review", "New Review"),
                    ("new_message", "New Message"),
                    ("payment_success", "Payment Success"),
                    ("payment_failed", "Payment Failed"),
                    ("payment_reminder", "Payment Reminder"),
                    ("roommate_request", "Roommate Request"),
                    ("roommate_approved", "Roommate Approved"),
                    ("fraud_flag", "Fraud Flag"),
                    ("kyc_sla_breach", "KYC SLA Breach"),
                    ("saved_search_match", "Saved Search Match"),
                    ("system", "System"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("endpoint", models.URLField(max_length=1000, unique=True)),
                ("auth", models.CharField(max_length=200)),
                ("p256dh", models.CharField(max_length=300)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["user"], name="notificatio_user_id_d7f78b_idx")],
            },
        ),
    ]
