# Generated by Django 5.2.16 on 2026-08-12 05:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0007_alter_notification_notification_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="meta",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
