# Generated by Django 5.2.16 on 2026-08-11 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0004_roomview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="area",
            field=models.CharField(
                choices=[
                    ("Dhanmondi", "Dhanmondi"),
                    ("Mirpur", "Mirpur"),
                    ("Gulshan", "Gulshan"),
                    ("Banani", "Banani"),
                    ("Mohammadpur", "Mohammadpur"),
                    ("Azimpur", "Azimpur"),
                    ("Uttara", "Uttara"),
                    ("Tejgaon", "Tejgaon"),
                    ("Badda", "Badda"),
                    ("Rampura", "Rampura"),
                    ("Banasree", "Banasree"),
                    ("Khilgaon", "Khilgaon"),
                    ("Motijheel", "Motijheel"),
                    ("Old Dhaka", "Old Dhaka"),
                    ("Bashundhara", "Bashundhara"),
                    ("Lalmatia", "Lalmatia"),
                    ("Shyamoli", "Shyamoli"),
                    ("Savar", "Savar"),
                    ("Keraniganj", "Keraniganj"),
                    ("Tongi", "Tongi"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="RoomImageHash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("phash_hex", models.CharField(max_length=16)),
                ("image_updated_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hash_entries",
                        to="rooms.roomimage",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_hashes",
                        to="rooms.room",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["phash_hex"], name="room_img_hash_idx")],
            },
        ),
    ]
