# Generated by Django 5.2.16 on 2026-08-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pricing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketstat",
            name="area",
            field=models.CharField(
                choices=[
                    ("Dhanmondi", "Dhanmondi"),
                    ("Mirpur", "Mirpur"),
                    ("Gulshan", "Gulshan"),
                    ("Banani", "Banani"),
                    ("Mohammadpur", "Mohammadpur"),
                    ("Azimpur", "Azimpur"),
                    ("Uttara", "Uttara"),
                    ("Tejgaon", "Tejgaon"),
                    ("Badda", "Badda"),
                    ("Rampura", "Rampura"),
                    ("Banasree", "Banasree"),
                    ("Khilgaon", "Khilgaon"),
                    ("Motijheel", "Motijheel"),
                    ("Old Dhaka", "Old Dhaka"),
                    ("Bashundhara", "Bashundhara"),
                    ("Lalmatia", "Lalmatia"),
                    ("Shyamoli", "Shyamoli"),
                    ("Savar", "Savar"),
                    ("Keraniganj", "Keraniganj"),
                    ("Tongi", "Tongi"),
                ],
                max_length=50,
            ),
        ),
    ]
