# Generated by Django 5.2.16 on 2026-08-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fraud", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fraudsignal",
            name="detector",
            field=models.CharField(
                choices=[
                    ("duplicate_listing", "Duplicate Listing"),
                    ("suspicious_price", "Suspicious Price"),
                    ("missing_images", "Missing Images"),
                    ("rapid_listing", "Rapid Listing"),
                    ("unverified_owner", "Unverified Owner"),
                    ("description_similarity", "Description Similarity"),
                    ("duplicate_image", "Duplicate Image"),
                ],
                max_length=30,
            ),
        ),
    ]
